# Site settings
title: 
header-img: img/home-bg.png
email: enciie@gmail.com
copyright_name: enciie
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: nancyjochang
github_username:  enciie
learn_profile: enciie
email_username: enciie@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
